### ISSUE TITLE
Faux highs with numeric attributes

### ISSUE THREAD

**Issue by mbojan** [statnet/statnet.data#3]
In `ergm` there are copies of `faux.magnolia.high` and `faux.mesa.high` but with numeric attributes (instead of e.g. text):

- `faux.magnolia.high.withnumericattributes`
- `faux.mesa.high.withnumericattributes`

Do we want to keep them in `statnet.data` or are these some sort of artifact that can be removed?

**Comment by mbojan** [comment]
@sgoodreau @martinamorris @krivit ?

**Comment by sgoodreau** [comment]
I think they are artifacts, and can be removed.

**Comment by mbojan** [comment]
Ok thanks @sgoodreau .
